/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java-library")
    alias(libs.plugins.spotless)
    alias(libs.plugins.spotbugs)
    checkstyle
    id("com.vanniktech.maven.publish") version "0.35.0"
}

group = "express.mvp"
version = "0.2.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

// Spotless configuration for Google Java Format
spotless {
    java {
        target("src/**/*.java")
        googleJavaFormat("1.32.0").aosp().reflowLongStrings()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}

// Checkstyle configuration
val checkstyleDir = file("${rootProject.projectDir}/config/checkstyle")

checkstyle {
    toolVersion = libs.versions.checkstyle.get()
    configDirectory.set(checkstyleDir)
    configFile = checkstyleDir.resolve("google_checks.xml")
    isIgnoreFailures = false
    maxWarnings = 0
    configProperties["suppressionFile"] = checkstyleDir.resolve("suppressions.xml").absolutePath
}

tasks.withType<Checkstyle>().configureEach {
    reports {
        xml.required.set(true)
        html.required.set(true)
    }
}

// SpotBugs configuration
spotbugs {
    toolVersion.set("4.9.8")
    ignoreFailures.set(false)
    showStackTraces.set(true)
    showProgress.set(true)
    effort.set(com.github.spotbugs.snom.Effort.MAX)
    reportLevel.set(com.github.spotbugs.snom.Confidence.LOW)
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach {
    enabled = true
    reports {
        create("html") {
            required.set(true)
            outputLocation.set(file("${layout.buildDirectory.get()}/reports/spotbugs/${name}.html"))
        }
        create("xml") {
            required.set(true)
            outputLocation.set(file("${layout.buildDirectory.get()}/reports/spotbugs/${name}.xml"))
        }
    }
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    // SpotBugs annotations for null-safety documentation
    compileOnly("com.github.spotbugs:spotbugs-annotations:4.9.8")

    testImplementation(platform("org.junit:junit-bom:5.10.0"))
    testImplementation("org.junit.jupiter:junit-jupiter")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.12.1")
        }
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}

tasks.jar {
    archiveBaseName.set("roray-ffm")
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(
        groupId = group.toString(),
        artifactId = "roray-ffm",
        version = version.toString(),
    )

    pom {
        name.set("roray-ffm")
        description.set("High-performance memory toolkit for Java's Foreign Function and Memory API.")
        inceptionYear.set("2025")
        url.set("https://github.com/mvp-express/roray-ffm-utils")

        licenses {
            license {
                name.set("The Apache License, Version 2.0")
                url.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
                distribution.set("http://www.apache.org/licenses/LICENSE-2.0.txt")
            }
        }

        developers {
            developer {
                id.set("mvp-express")
                name.set("MVP Express Team")
                email.set("hi@mvp.express")
            }
        }

        scm {
            url.set("https://github.com/mvp-express/roray-ffm-utils")
            connection.set("scm:git:git://github.com/mvp-express/roray-ffm-utils.git")
            developerConnection.set("scm:git:ssh://git@github.com/mvp-express/roray-ffm-utils.git")
        }
    }
}
